# Generated by Django 4.0.3 on 2022-03-07 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='budget',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Salary should be positive!')]),
        ),
    ]
