# Generated by Django 4.0.3 on 2022-03-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_instructor_dept_name_remove_student_dept_name'),
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='i_id',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='prereq_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='sec_id',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='sec_id',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='year',
        ),
        migrations.DeleteModel(
            name='Time_slot',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Prereq',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Takes',
        ),
        migrations.DeleteModel(
            name='Teaches',
        ),
    ]
