# Generated by Django 4.0.3 on 2022-03-10 09:26

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_instructor_dept_name_remove_student_dept_name'),
        ('university', '0003_remove_advisor_i_id_remove_advisor_s_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=7)),
                ('capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4, message='No more than 4 digits.')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Credits should be positive values.')])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(default='Comp. Sci.', max_length=20)),
                ('building', models.CharField(max_length=15)),
                ('budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Salary should be positive!')])),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(max_length=8)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6)),
                ('year', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.datetime(1701, 1, 1, 0, 0)), django.core.validators.MaxValueValidator(datetime.datetime(2100, 1, 1, 0, 0))])),
                ('time_slot_id', models.CharField(max_length=4)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionBuilding', to='university.classroom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionRoomNumber', to='university.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Time_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot_id', models.CharField(max_length=4)),
                ('day', models.CharField(choices=[('sa', 'Saturday'), ('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuseday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday')], max_length=9)),
                ('start_hr', models.TimeField()),
                ('end_hr', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='TeachesId', serialize=False, to='users.instructor')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesCourseId', to='university.section')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesSectionId', to='university.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachesSemester', to='university.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeachesYaer', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.student')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesCourseId', to='university.section')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesSectionId', to='university.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesSemester', to='university.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TakesYear', to='university.section')),
            ],
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Current', to='university.course')),
                ('prereq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prereq', to='university.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.department'),
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
