# Generated by Django 4.0.3 on 2022-03-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_slot',
            name='time_slot_id',
        ),
    ]
