# Generated by Django 4.0.3 on 2022-03-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_time_slot_time_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.time_slot'),
        ),
    ]
