# Generated by Django 4.0.3 on 2022-03-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_rename_course_id_course_courseid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseId',
            new_name='courseid',
        ),
    ]
