# Generated by Django 4.0.3 on 2022-03-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_rename_courseid_course_courseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prereq',
            old_name='courseId',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='courseId',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='courseId',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='courseId',
            new_name='courseid',
        ),
    ]
