# Generated by Django 4.0.3 on 2022-03-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_rename_courseid_prereq_courseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseid',
            field=models.CharField(db_column='courseid', max_length=8, primary_key=True, serialize=False),
        ),
    ]
