# Generated by Django 4.0.3 on 2022-03-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor_dept_name_student_dept_name'),
        ('university', '0014_alter_takes_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaches',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
