# Generated by Django 4.0.3 on 2022-04-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor_dept_name_student_dept_name'),
        ('university', '0015_teaches_instructor_alter_teaches_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarksInstructorId', to='users.instructor')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MarksSectionId', to='university.section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarksStudentId', to='users.student')),
            ],
        ),
    ]
