# Generated by Django 4.0.3 on 2022-04-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MarksTakeId', to='university.takes'),
        ),
    ]
