insert into university_course (course_id, title, dept_name_id, credits) values('760', 'How to Groom your Cat', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('629', 'Finite Element Analysis', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('762', 'The Monkeys', '3', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('242', 'Rock and Roll', '5', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('482', 'FOCAL Programming', '17', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('581', 'Calculus', '6', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('843', 'Environmental Law', '18', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('679', 'The Beatles', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('704', 'Marine Mammals', '12', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('774', 'Game Programming', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('591', 'Shakespeare', '6', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('319', 'World History', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('960', 'Tort Law', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('274', 'Corporate Law', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('426', 'Video Gaming', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('852', 'World History', '15', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('408', 'Bankruptcy', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('808', 'Organic Chemistry', '7', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('902', 'Existentialism', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('730', 'Quantum Mechanics', '19', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('362', 'Embedded Systems', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('341', 'Quantum Mechanics', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('582', 'Marine Mammals', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('867', 'The IBM 360 Architecture', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('169', 'Marine Mammals', '19', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('680', 'Electricity and Magnetism', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('227', 'Elastic Structures', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('991', 'Transaction Processing', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('366', 'Computational Biology', '7', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('376', 'Cost Accounting', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('489', 'Journalism', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('663', '12', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('461', 'Physical Chemistry', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('105', 'Image Processing', '14', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('407', 'Industrial Organization', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('254', 'Security', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('998', 'Immunology', '1', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('457', 'Systems Software', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('401', 'Sanitary Engineering', '15', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('127', 'Thermodynamics', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('399', 'RPG Programming', '6', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('949', 'Japanese', '9', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('496', 'Aquatic Chemistry', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('334', 'International Trade', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('544', 'Differential Geometry', '16', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('451', 'Database System Concepts', '6', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('190', 'Romantic Literature', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('630', 'Religion', '7', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('761', 'Existentialism', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('804', 'Introduction to Burglary', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('781', 'Compiler Design', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('805', 'Composition and Literature', '16', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('318', '12', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('353', 'Operating Systems', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('394', 'C  Programming', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('137', 'Manufacturing', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('192', 'Drama', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('681', 'Medieval Civilization or Lack Thereof', '7', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('377', 'Differential Geometry', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('959', 'Bacteriology', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('235', 'International Trade', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('421', 'Aquatic Chemistry', '15', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('647', 'Service-Oriented Architectures', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('598', 'Number Theory', '8', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('858', 'Sailing', '18', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('487', 'Physical Chemistry', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('133', 'Antidisestablishmentarianism in Modern America', '2', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('267', 'Hydraulics', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('200', 'The Music of the Ramones', '8', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('664', 'Elastic Structures', '7', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('599', 'Mechanics', '17', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('456', 'Hebrew', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('558', 'Environmental Law', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('919', 'Computability Theory', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('546', 'Creative Writing', '20', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('969', 'The Monkeys', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('877', 'Composition and Literature', '2', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('337', 'Differential Geometry', '16', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('983', 'Virology', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('603', 'Care and Feeding of Cats', '16', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('747', 'International Practicum', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('659', '12', '18', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('559', 'Martian History', '2', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('403', 'Immunology', '2', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('436', 'Stream Processing', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('656', 'Groups and Rings', '1', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('731', 'The Music of Donovan', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('820', 'Assembly Language Programming', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('898', 'Petroleum Engineering', '5', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('545', 'International Practicum', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('893', 'Systems Software', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('818', 'Environmental Law', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('618', 'Thermodynamics', '7', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('416', 'Data Mining', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('716', 'Medieval Civilization or Lack Thereof', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('130', 'Differential Geometry', '4', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('476', 'International Communication', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('101', 'Diffusion and Phase Transformation', '20', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('123', 'Differential Equations', '20', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('209', 'International Trade', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('352', 'Compiler Design', '17', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('393', 'Aerodynamics', '10', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('795', 'Death and Taxes', '5', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('577', 'The Music of Dave Edmunds', '19', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('584', 'Computability Theory', '9', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('864', 'Heat Transfer', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('594', 'Cognitive Psychology', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('802', 'African History', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('692', 'Cat Herding', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('258', 'Colloid and Surface Chemistry', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('748', 'Tort Law', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('770', 'European History', '6', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('340', 'Corporate Law', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('158', 'Elastic Structures', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('276', 'Game Design', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('626', 'Multimedia Design', '3', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('696', 'Heat Transfer', '5', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('239', 'The Music of the Ramones', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('962', 'Animal Behavior', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('527', 'Graphics', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('275', 'Romantic Literature', '10', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('549', 'Banking and Finance', '14', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('974', 'Astronautics', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('897', 'How to Succeed in Business Without Really Trying', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('359', 'Game Programming', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('345', 'Race Car Driving', '8', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('371', 'Milton', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('284', 'Topology', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('642', 'Video Gaming', '17', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('769', 'Logic', '19', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('947', 'Real-Time Database Systems', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('265', 'Thermal Physics', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('927', 'Differential Geometry', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('694', 'Optics', '18', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('580', 'The Music of Dave Edmunds', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('324', 'Ponzi Schemes', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('349', 'Networking', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('392', 'Recursive Function Theory', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('735', 'Greek Tragedy', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('702', 'Arabic', '2', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('458', 'The Renaissance', '1', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('348', 'Compiler Design', '19', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('500', 'Networking', '14', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('494', 'Automobile Mechanics', '6', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('411', 'Music of the 80s', '20', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('493', 'Music of the 50s', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('396', 'C  Programming', '10', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('810', 'Mobile Computing', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('631', 'Plasma Physics', '19', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('486', '8', '12', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('963', 'Groups and Rings', '10', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('445', 'Biostatistics', '11', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('292', 'Electron Microscopy', '7', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('830', 'Sensor Networks', '14', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('604', 'UNIX System Programmming', '16', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('857', 'UNIX System Programmming', '12', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('304', 'Music 2 New for your Instructor', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('922', 'Microeconomics', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('571', 'Plastics', '9', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('628', 'Existentialism', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('841', 'Fractal Geometry', '20', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('586', 'Image Processing', '11', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('139', 'Number Theory', '7', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('666', 'Multivariable Calculus', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('443', 'Journalism', '4', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('195', 'Numerical Methods', '12', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('634', '	Astronomy', '13', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('224', 'International Finance', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('791', 'Operating Systems', '5', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('875', 'Bioinformatics', '13', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('958', 'Fiction Writing', '20', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('415', 'Numerical Methods', '2', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('442', 'Strength of Materials', '15', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('468', 'Fractal Geometry', '1', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('270', 'Music of the 90s', '18', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('966', 'Sanitary Engineering', '3', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('793', 'Decison Support Systems', '1', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('236', 'Design and Analysis of Algorithms', '20', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('792', 'Image Processing', '8', 3);
insert into university_course (course_id, title, dept_name_id, credits) values('561', 'The Music of Donovan', '19', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('344', 'Quantum Mechanics', '8', 4);
insert into university_course (course_id, title, dept_name_id, credits) values('780', '12', '17', 3);