-- insert into university_department (dept_name, building, budget) values('Civil Eng.', 'Chandler', 255041.46);
-- insert into university_department (dept_name, building, budget) values('Biology', 'Candlestick', 647610.55);
-- insert into university_department (dept_name, building, budget) values('History', 'Taylor', 699140.86);
-- insert into university_department (dept_name, building, budget) values('Physics', 'Wrigley', 942162.76);
-- insert into university_department (dept_name, building, budget) values('Marketing', 'Lambeau', 210627.58);
-- insert into university_department (dept_name, building, budget) values('Pol. Sci.', 'Whitman', 573745.09);
-- insert into university_department (dept_name, building, budget) values('English', 'Palmer', 611042.66);
-- insert into university_department (dept_name, building, budget) values('Accounting', 'Saucon', 441840.92);
-- insert into university_department (dept_name, building, budget) values('Comp. Sci.', 'Lamberton', 106378.69);
-- insert into university_department (dept_name, building, budget) values('Languages', 'Linderman', 601283.60);
-- insert into university_department (dept_name, building, budget) values('Finance', 'Candlestick', 866831.75);
-- insert into university_department (dept_name, building, budget) values('Geology', 'Palmer', 406557.93);
-- insert into university_department (dept_name, building, budget) values('Cybernetics', 'Mercer', 794541.46);
-- insert into university_department (dept_name, building, budget) values('Astronomy', 'Taylor', 617253.94);
-- insert into university_department (dept_name, building, budget) values('Athletics', 'Bronfman', 734550.70);
-- insert into university_department (dept_name, building, budget) values('Statistics', 'Taylor', 395051.74);
-- insert into university_department (dept_name, building, budget) values('Psychology', 'Thompson', 848175.04);
-- insert into university_department (dept_name, building, budget) values('Math', 'Brodhead', 777605.11);
-- insert into university_department (dept_name, building, budget) values('Elec. Eng.', 'Main', 276527.61);
-- insert into university_department (dept_name, building, budget) values('Mech. Eng.', 'Rauch', 520350.65);
-- insert into university_classroom (building, room_number, capacity) values ('Packard', '101', '500');
-- insert into university_classroom (building, room_number, capacity) values ('Painter', '514', '10');
-- insert into university_classroom (building, room_number, capacity) values ('Taylor', '3128', '70');
-- insert into university_classroom (building, room_number, capacity) values ('Watson', '100', '30');
-- insert into university_classroom (building, room_number, capacity) values ('Watson', '120', '50');
-- insert into university_classroom (building, room_number, capacity) values('Lamberton', 134, 10);
-- insert into university_classroom (building, room_number, capacity) values('Chandler', 375, 10);
-- insert into university_classroom (building, room_number, capacity) values('Fairchild', 145, 27);
-- insert into university_classroom (building, room_number, capacity) values('Nassau', 45, 92);
-- insert into university_classroom (building, room_number, capacity) values('Grace', 40, 34);
-- insert into university_classroom (building, room_number, capacity) values('Whitman', 134, 120);
-- insert into university_classroom (building, room_number, capacity) values('Lamberton', 143, 10);
-- insert into university_classroom (building, room_number, capacity) values('Taylor', 812, 115);
-- insert into university_classroom (building, room_number, capacity) values('Saucon', 113, 109);
-- insert into university_classroom (building, room_number, capacity) values('Painter', 86, 97);
-- insert into university_classroom (building, room_number, capacity) values('Alumni', 547, 26);
-- insert into university_classroom (building, room_number, capacity) values('Alumni', 143, 47);
-- insert into university_classroom (building, room_number, capacity) values('Drown', 757, 18);
-- insert into university_classroom (building, room_number, capacity) values('Saucon', 180, 15);
-- insert into university_classroom (building, room_number, capacity) values('Whitman', 434, 32);
-- insert into university_classroom (building, room_number, capacity) values('Saucon', 844, 24);
-- insert into university_classroom (building, room_number, capacity) values('Bronfman', 700, 12);
-- insert into university_classroom (building, room_number, capacity) values('Polya', 808, 28);
-- insert into university_classroom (building, room_number, capacity) values('Gates', 707, 65);
-- insert into university_classroom (building, room_number, capacity) values('Gates', 314, 10);
-- insert into university_classroom (building, room_number, capacity) values('Main', 45, 30);
-- insert into university_classroom (building, room_number, capacity) values('Taylor', 183, 71);
-- insert into university_classroom (building, room_number, capacity) values('Power', 972, 10);
-- insert into university_classroom (building, room_number, capacity) values('Garfield', 119, 59);
-- insert into university_classroom (building, room_number, capacity) values('Rathbone', 261, 60);
-- insert into university_classroom (building, room_number, capacity) values('Stabler', 105, 113);
-- insert into university_classroom (building, room_number, capacity) values('Power', 717, 12);
-- insert into university_classroom (building, room_number, capacity) values('Main', 425, 22);
-- insert into university_classroom (building, room_number, capacity) values('Lambeau', 348, 51);
-- insert into university_classroom (building, room_number, capacity) values('Chandler', 804, 11);
                                                                                                                            -- '747', '1', 'Spring', '2004-01-01', '25', '25', 'K'
-- insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values ('747', '1', 'Spring', '2004-01-01', '25', '25', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('443', '1', 'Spring', '2010-01-01', '20', '20', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('893', '1', 'Fall', '2007-01-01', '8', '8', '4');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('663', '1', 'Spring', '2005-01-01', '8', '8', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('457', '1', 'Spring', '2001-01-01', '21', '21', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('445', '1', 'Spring', '2001-01-01', '16', '16', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('559', '1', 'Fall', '2002-01-01', '6', '6', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('239', '1', 'Fall', '2006-01-01', '27', '27', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('802', '1', 'Spring', '2003-01-01', '14', '14', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('158', '1', 'Fall', '2008-01-01', '20', '20', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('735', '1', 'Spring', '2003-01-01', '18', '18', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('237', '1', 'Spring', '2008-01-01', '32', '32', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('338', '1', 'Spring', '2007-01-01', '8', '8', '9');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('376', '1', 'Fall', '2006-01-01', '32', '32', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('927', '1', 'Fall', '2002-01-01', '19', '19', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('692', '1', 'Spring', '2010-01-01', '27', '27', '10');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('867', '1', 'Fall', '2006-01-01', '27', '27', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('561', '1', 'Fall', '2006-01-01', '26', '26', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('604', '1', 'Spring', '2009-01-01', '22', '22', '13');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('974', '1', 'Fall', '2003-01-01', '23', '23', '14');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('959', '1', 'Fall', '2006-01-01', '19', '19', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('702', '1', 'Spring', '2001-01-01', '14', '14', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('631', '1', 'Spring', '2007-01-01', '27', '27', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('334', '1', 'Fall', '2009-01-01', '13', '13', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('274', '1', 'Fall', '2002-01-01', '33', '33', '13');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('366', '1', 'Fall', '2005-01-01', '21', '21', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('545', '1', 'Fall', '2001-01-01', '19', '19', '17');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('486', '1', 'Fall', '2009-01-01', '11', '11', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('426', '1', 'Spring', '2006-01-01', '6', '6', '9');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('258', '1', 'Fall', '2007-01-01', '26', '26', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('972', '1', 'Spring', '2009-01-01', '27', '27', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('349', '1', 'Spring', '2008-01-01', '14', '14', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('415', '1', 'Fall', '2010-01-01', '6', '6', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('137', '1', 'Spring', '2002-01-01', '8', '8', '10');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('304', '1', 'Fall', '2009-01-01', '12', '12', '14');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('468', '1', 'Fall', '2005-01-01', '34', '34', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('748', '1', 'Fall', '2003-01-01', '19', '19', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('694', '1', 'Fall', '2002-01-01', '17', '17', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('345', '1', 'Spring', '2008-01-01', '27', '27', '16');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('352', '1', 'Spring', '2006-01-01', '34', '34', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('581', '1', 'Spring', '2005-01-01', '16', '16', '9');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('493', '1', 'Spring', '2010-01-01', '6', '6', '14');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('795', '1', 'Spring', '2004-01-01', '12', '12', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('793', '1', 'Spring', '2002-01-01', '9', '9', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('237', '2', 'Fall', '2009-01-01', '8', '8', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('362', '1', 'Fall', '2005-01-01', '12', '12', '10');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('642', '1', 'Fall', '2004-01-01', '14', '14', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('808', '1', 'Fall', '2003-01-01', '23', '23', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('679', '1', 'Spring', '2010-01-01', '21', '21', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('629', '1', 'Spring', '2003-01-01', '31', '31', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('400', '1', 'Spring', '2007-01-01', '34', '34', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('599', '1', 'Spring', '2003-01-01', '35', '35', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('760', '1', 'Spring', '2004-01-01', '29', '29', '16');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('843', '1', 'Fall', '2010-01-01', '8', '8', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('200', '1', 'Spring', '2007-01-01', '19', '19', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('443', '2', 'Spring', '2002-01-01', '24', '24', '2');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('612', '1', 'Fall', '2007-01-01', '12', '12', '9');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('169', '1', 'Spring', '2007-01-01', '25', '25', '16');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('791', '1', 'Spring', '2006-01-01', '23', '23', '14');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('867', '2', 'Fall', '2010-01-01', '6', '6', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('489', '1', 'Fall', '2007-01-01', '12', '12', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('158', '2', 'Spring', '2008-01-01', '13', '13', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('242', '1', 'Fall', '2009-01-01', '8', '8', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('960', '1', 'Fall', '2009-01-01', '6', '6', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('421', '1', 'Fall', '2004-01-01', '24', '24', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('105', '1', 'Fall', '2009-01-01', '7', '7', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('591', '1', 'Spring', '2005-01-01', '19', '19', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('192', '1', 'Fall', '2002-01-01', '23', '23', '4');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('362', '2', 'Fall', '2006-01-01', '16', '16', '16');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('270', '1', 'Spring', '2010-01-01', '32', '32', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('461', '1', 'Fall', '2002-01-01', '33', '33', '17');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('704', '1', 'Spring', '2008-01-01', '13', '13', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('626', '1', 'Fall', '2006-01-01', '12', '12', '4');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('105', '2', 'Fall', '2002-01-01', '27', '27', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('696', '1', 'Spring', '2002-01-01', '19', '19', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('962', '1', 'Spring', '2008-01-01', '9', '9', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('362', '3', 'Spring', '2008-01-01', '22', '22', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('852', '1', 'Spring', '2008-01-01', '24', '24', '8');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('949', '1', 'Fall', '2007-01-01', '19', '19', '4');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('482', '1', 'Fall', '2005-01-01', '20', '20', '14');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('527', '1', 'Fall', '2004-01-01', '14', '14', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('476', '1', 'Fall', '2010-01-01', '18', '18', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('991', '1', 'Spring', '2008-01-01', '6', '6', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('408', '1', 'Spring', '2007-01-01', '13', '13', '7');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('319', '1', 'Spring', '2003-01-01', '30', '30', '11');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('400', '2', 'Fall', '2003-01-01', '33', '33', '3');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('401', '1', 'Fall', '2003-01-01', '19', '19', '16');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('960', '2', 'Fall', '2006-01-01', '32', '32', '15');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('571', '1', 'Spring', '2004-01-01', '28', '28', '10');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('468', '2', 'Fall', '2007-01-01', '32', '32', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('735', '2', 'Spring', '2010-01-01', '27', '27', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('169', '2', 'Fall', '2002-01-01', '18', '18', '12');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('496', '1', 'Fall', '2001-01-01', '13', '13', '10');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('200', '2', 'Fall', '2002-01-01', '7', '7', '5');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('875', '1', 'Spring', '2005-01-01', '32', '32', '17');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('603', '1', 'Fall', '2003-01-01', '13', '13', '17');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('408', '2', 'Spring', '2003-01-01', '27', '27', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('338', '2', 'Spring', '2006-01-01', '31', '31', '6');
insert into university_section (course_id_id, sec_id, semester, year, building_id, room_number_id, time_slot_id_id) values('864', '1', 'Spring', '2006-01-01', '28', '28', '5');