# Generated by Django 4.0.3 on 2022-03-07 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instructor_dept_name_student_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='salary',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8, message='No more than 8 digits!'), django.core.validators.MinValueValidator(29000.0, 'Salary should be more than $29000!')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='tot_cred',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Credits should be positive values.')]),
        ),
    ]
